project:
  type: website
  output-dir: docs

website:
  title: "Bayesian Analysis in R and Stan"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar: true
  
  sidebar:
    style: "floating"
    search: true
    contents:
    - index.qmd
    - auto: "*"
    border: true
    
  page-footer:
    border: true
    left: Copyright 2024 - Josh Tyler
    right:
      - text: "Probabilistic Programming and its applications in Evolution, Biodiversity & Health"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
    code-background: true

editor: visual

