project:
  type: website
  output-dir: docs


website:
  title: "Adventures in Bayesian Analysis"
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true
  search: 
    type: textbox
  
  
  navbar: 
    tools:
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/JTyler13/Adventures-in-Bayesian-Analysis
        - text: Report a Bug or Issue
          href:  https://github.com/JTyler13/Adventures-in-Bayesian-Analysis/issues/new

    
  sidebar:
    style: "floating"
    contents:
    - index.qmd
    - auto: "*"
    border: true
    collapse-level: 2
    
    
  page-footer:
    border: true
    background: "#45B39D"
    left: Copyright 2024 - Josh Tyler
    right: 
      - text: "Probabilistic Programming and its applications in Evolution, Biodiversity & Health"

format:
  html:
    theme: 
    - minty
    - custom.scss
    css: styles.css
    toc: true
    page-layout: article
    code-background: true

editor: visual

