project:
  type: website
  output-dir: docs

website:
  title: "An Adventure in Bayesian Analysis"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  
  navbar: 
    tools:
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/JTyler13/Bayesian-Analysis-in-R-and-Stan
        - text: Report a Bug or Issue
          href:  https://github.com/JTyler13/Bayesian-Analysis-in-R-and-Stan/issues/new
  
  sidebar:
    style: "floating"
    contents:
    - index.qmd
    - auto: "*"
    border: true
    collapse-level: 2
    search: true
    
  page-footer:
    border: true
    left: Copyright 2024 - Josh Tyler
    right: 
      - text: "Probabilistic Programming and its applications in Evolution, Biodiversity & Health"

format:
  html:
    theme: 
    - minty
    - custom.scss
    css: styles.css
    toc: true
    page-layout: article
    code-background: true

editor: visual

